### ISSUE TITLE
Is it possible to set resolution for the output?

### ISSUE THREAD

**Issue by virtanum** [tshino/softcam#33]
Is it possible to set resolution for the output?

I'd like to set aspect ratio manually, doesn't matter if I have to keep updating the registry until I get the one that suits me.

I'm having trouble getting my camera settings to run in Bluestacks as it is, so I'm going to try your dll solution wondering if their app is going to take the dll in.

Also, is this code capable of changing the Win10 native dll settings? 

Thanks in advance and sorry if my questions are stupid.

**Comment by tshino** [comment]
Thank you for your interest in this software! Sorry for the late reply.

You are trying to use a camera with non-square pixels on some application, is this correct?
I mean it is the case the ratio between width and height in pixels does not match the actual aspect ratio of the image.

I guess the underlying DirectShow API provides the capability to handle such cases.
But, Softcam assumes that the input images are with square pixels.

**Comment by tshino** [comment]
If you have further question or comments on this issue, please feel free to reopen it.
