### ISSUE TITLE
Softcam doesn't appear in camera list on discord

### ISSUE THREAD

**Issue by rp25** [tshino/softcam#47]
Softcam doesn't appear in camera list on discord windows app on windows 10. OBS virtual cam appears in Camera list. Softcam virtual does appear in other apps (web browser, OBS, Zoom)

**Comment by tshino** [comment]
Thank you for reporting!
I could reproduce this issue.
I will investigate it.

**Comment by risingblock** [comment]
Hi @tshino , I think it is working with the 32-bit version of softcam. 

I see your readme says: 
```
Note: The DLL softcam.dll built above is a 64-bit DLL file. In order to support 32-bit camera applications as well, you should build 32-bit softcam.dll too by choosing the platform Win32. The 32-bit DLL file will be put in the dist/bin/Win32 directory.
```

So is the best solution to package two versions of the .dll with the app? softcam-32.dll & softcam-64.dll. 

What do you recommend? 

Thanks for your hard work.

**Comment by tshino** [comment]
Nice! Yes, that's right!
When I was testing, I missed that the Discord app is 32-bit.

The recommended solution is:
- provide both 32-bit and 64-bit versions of Softcam
- let users install both versions
- use either one in your application

@risingblock,
Thanks for your help!
