### ISSUE TITLE
Changing dll name that is searched for

### ISSUE THREAD

**Issue by KaiH-0** [tshino/softcam#8]
I keep getting an error saying softcam.dll isn't found as I want to change the name of the dll.
I have installed the dll under a different name. It's just when I run the sender exe, it is looking for the wrong name.

Where is the piece of code to tell it to look for a different name, for example cam.dll

Thanks in advance.

**Comment by tshino** [comment]
Hello, Kyle.

Clarifying your situation, my understanding is that you

1. built the `softcam.dll`,
2. modified the DLL name,
3. installed the DLL with the modified name,
4. built the `sender.exe` and ran it,
5. and got the error.

Is this correct?

If so, I think, the name of DLL that `sender.exe` is searching comes out from the import library `softcam.lib` , which is built together with `softcam.dll` at the first step of the above steps.

To modify the name, I think you can change the Target Name property in the configurations properties when building `softcam.dll`.

**Comment by KaiH-0** [comment]
I managed to fix it with your comment, the problem was I had changed the target name for the softcam but didn't change the softcamcore target name. After that I changed my libs from softcam.lib to my lib and it worked!
